meta:
    flow: VHDLClassic

DESIGN_NAME: spad_env_f_bit
VHDL_FILES: dir::spad_env_f_bit.vhd
CLOCK_PORT: clk
CLOCK_PERIOD: 5 # 5ns = 200MHz

# Reduce wasted space
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6

# Absolute die size
FP_SIZING: absolute
DIE_AREA: [0, 0, 75, 75]

FP_PIN_ORDER_CFG: dir::pins.cfg

# Macro in a macro
PDN_MULTILAYER: true
RT_MAX_LAYER: Metal5
FP_PDN_HORIZONTAL_LAYER: Metal5
FP_PDN_VERTICAL_LAYER: Metal4
