# LibreLane configuration file

DESIGN_NAME: heichips25_usb_cdc
VERILOG_FILES: 
- dir::../src/heichips25_usb_cdc.sv
- dir::../src/usb_cdc/usb_cdc/usb_cdc.v
- dir::../src/usb_cdc/usb_cdc/phy_rx.v
- dir::../src/usb_cdc/usb_cdc/phy_tx.v
- dir::../src/usb_cdc/usb_cdc/sie.v
- dir::../src/usb_cdc/usb_cdc/ctrl_endp.v
- dir::../src/usb_cdc/usb_cdc/in_fifo.v
- dir::../src/usb_cdc/usb_cdc/out_fifo.v
- dir::../src/usb_cdc/usb_cdc/bulk_endp.v

CLOCK_PORT: clk
CLOCK_PERIOD: 20.83 # 20.83ns = 48MHz

# Reduce wasted space
TOP_MARGIN_MULT: 1
BOTTOM_MARGIN_MULT: 1
LEFT_MARGIN_MULT: 6
RIGHT_MARGIN_MULT: 6

# Absolute die size
FP_SIZING: absolute

# Small DEF template
DIE_AREA: [0, 0, 500, 200]
FP_DEF_TEMPLATE: dir::def/heichips25_template_small_usb.def

# Large DEF template
#DIE_AREA: [0, 0, 500, 415]
#FP_DEF_TEMPLATE: dir::def/heichips25_template_large.def

# Don't use power rings or TopMetal2 layer
PDN_MULTILAYER: false
RT_MAX_LAYER: TopMetal1

# reserve space for the logo
#PL_SOFT_OBSTRUCTIONS: 
#- [403, 135, 468, 190]
#PDN_OBSTRUCTIONS:
# - [TopMetal1, 335, 41, 461, 168]

# Enable for better SystemVerilog support
#USE_SLANG: true

MACROS:
  spad_env_f_bit:
    gds:
      - dir::../spad_env_f_bit/macro/gds/spad_env_f_bit.gds
    lef:
      - dir::../spad_env_f_bit/macro/lef/spad_env_f_bit.lef
    nl:
      - dir::../spad_env_f_bit/macro/nl/spad_env_f_bit.nl.v
    spef:
      nom:
        - dir::../spad_env_f_bit/macro/spef/nom/spad_env_f_bit.nom.spef
    instances:
      i_spad_env_f_bit:
        location: [50, 5]
        orientation: N

PDN_MACRO_CONNECTIONS:
  - "i_spad_env_f_bit VPWR VGND VPWR VGND"

# Custom PDN config
FP_PDN_CFG: dir::pdn_cfg.tcl
