// Auto-generated by LibreLane
module heichips25_usb_cdc(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input[7:0] ui_in,
  output[7:0] uo_out,
  input[7:0] uio_in,
  output[7:0] uio_out,
  output[7:0] uio_oe,
  input ena,
  input clk,
  input rst_n,
  output usb_dp_en_o,
  input usb_dp_rx_i,
  output usb_dp_tx_o,
  output usb_dn_en_o,
  input usb_dn_rx_i,
  output usb_dn_tx_o,
  output usb_dp_up_o
);
endmodule
